In [1]:
import pandas as pd

In [2]:
import draft

ModuleNotFoundError: No module named 'app.draft'; 'app' is not a package

In [3]:
projections_path = '/Users/jjcaine/Downloads/rotowire-projections.xlsx'

In [4]:
df = pd.read_excel(projections_path)

In [5]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Projected Stats,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Name,Team,Pos,Eligibility,GP,MIN,PTS,REB,AST,STL,BLK,3PM,TO,2DBL,3DBL
1,Adama Sanogo,Connecticut,C,Junior,34,32.6,17.3,9.8,1.1,1,2.1,0,2.5,0.4,0
2,Brandon Slater,Villanova,G,Senior,37,32.4,15.4,4.6,2,1.3,0.3,1.1,1.5,0,0
3,Posh Alexander,St. John's,G,Junior,32,33.6,17.6,4.8,6.1,2.5,0.2,0.5,2.6,0.1,0
4,Caleb Daniels,Villanova,G,Senior,37,34.7,15.2,5.1,1.4,1,0.3,2.5,1.7,0.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,Stevie Mitchell,Marquette,G,Sophomore,32,18.2,5.8,2.4,1.5,1.2,0.2,0.4,1.2,0,0
76,Corey Floyd,Providence,G,Freshman,32,17,5.2,2.5,1.7,0.6,0.2,0.9,1,0,0
77,Ryan Mutombo,Georgetown,C,Sophomore,32,18.1,4,4.6,0.2,0.3,1.4,0,0.8,0.1,0
78,Mason Miller,Creighton,F,Freshman,32,15.2,3.5,3.2,1.3,0.7,0.2,0.6,1.1,0,0
79,Chris Arcidiacono,Villanova,G,Senior,37,10.7,2.2,1.1,0.7,0.3,0,0.4,0.3,0,0